### ISSUE TITLE
How to add alphabetic and numerical keyboards to the Pictograph-Keyboard ?

### ISSUE THREAD

**Issue by issacpeter** [flide/Emoji-Keyboard#2]
Hi, how can i add alphabetic keyboard and numeric keyboard to Pictograph-Keyboard ? Can I use android.inputmethodservice.KeyboardView for alphabetic keyboard and switch between them?

**Comment by flide** [comment]
Take a look at an another project of mine - 8Vim, https://github.com/flide/8Vim, it has the implementation you are looking for, and it is far more extendable as I did not create this one with that kind of extension in mind.

**Comment by issacpeter** [comment]
Sorry for late reply. I will checkout 8Vim. Thanks for the  response.
